name: "PHP CodeSniffer Validations"

on: [ push]
jobs:
  validate-code-style:
    name: PSR-12 Code style
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with: 
          php-version: '8.0.3'
          tools: phpstan, composer

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Get Composer Cache Directory
      id: composer-cache
      run: echo "::set-output name=dir::$(composer config cache-file-dir)"
      
    - name: Cache Composer Dependencies 
      uses: actions/cache@v2
      with:
        path: ~/.composer/cache/
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composer-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress
      
    - name: Install PHP_CodeSniffer composer package
      run: composer global require "squizlabs/php_codesniffer=*"
      
    - name: Validate PSR-12 Code Style
      run: ~/.composer/vendor/bin/phpcs

    - name: Run PHPStan
      run: phpstan analyse src

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
